project:
  type: book
  output-dir: docs

book:
  title: "Learning Diary - CASA0023: Remotely Sensing Cities and Environment"
  author: "Jasmine Mahdani"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    number-sections: true
    number-depth: 2
    toc: true

editor: visual

