# Personal Introduction {.unnumbered}

My name is Jasmine Mahdani and I am from Indonesia. I graduated from ITB (Bandung Institute of Technology) in 2022, majoring in Geodesy and Geomatic Engineering. During my undergraduate years, I had been actively engaged in research particularly for urban related issues using GIS and remote sensing. My research topic focus on water and sanitation access, slum identification, and disaster risk assessment. My enthusiasm to urban issues and GIS continues after I graduate that leads me to choose urban spatial researcher as my career path. However, doing spatial analysis for urban issues is quite tricky because the coverage area is relatively small and finding open source detailed data set in Indonesia is extremely hard. Moreover, I also have limited knowledge on how urban system works. Therefore, I decided to pursue master degree in Urban Spatial Science at UCL (University College London) to deepen my knowledge in urban analytics and to support my career path as a researcher. In Urban Spatial Science, I take the Urban Modelling and Simulation pathway and Remotely Sensing Cities and Environment modules in hope I can answer the challenge of using open sourced medium spatial resolution remote sensing data for urban research that mostly have small coverage area.
