# Introduction to Remote Sensing

## Summary: Remote Sensing Definition and How it Works

Remote sensing is the practice of obtaining information about the Earth’s surface, using images acquired from airborne or spaceborne vehicles by measuring reflected, emitted, or returned electromagnetic radiation [@defries2013]. The objective of this technology is to provide observation of physical parameter in a mapping frame at a given time period [@toth2016].

Remote sensing captures the electromagnetic (EM) radiation that is reflected from earth’s surface. EM wave is an energy that travels through the light. All matters with absolute temperature above zero reflect and emit EM waves of various length [@kerle2004]. A material that fully capable of absorbing and re-emitting all EM energy that it receives is called a blackbody, but it is rare and most natural objects only absorb some of the energy. The difference in how objects absorb and reflect energy is what’s make every earth’s feature has its own signature characteristic which is recorded as digital number (DN) in each pixel of images using the sensors.

In remote sensing, there are two type of sensors, passive and active that are used for different applications. Most sensors use passive systems which can only capture the reflection of sun’s energy and work during daylight. Therefore, this sensors’ orbit sometimes are set to follow’s the sun (sun-synchronous). The electromagnetic spectrum recorded by the sensors range from ultraviolet (UV), visible (red, green, blue), infrared (IR), and microwave. Meanwhile, active remote sensing can radiate its own energy and measure the amount of radiation returned to the sensor. Active sensors can penetrate through clouds and won’t be affected by daylight or weather conditions. Example of active sensors included SAR and LIDAR.

Although remote sensing is great for collecting data in inaccessible area and cheaper for mapping large areas, there are 4 type of resolution that needs to be considered when using it: spatial, spectral, temporal, and radiometric. Spatial resolution refers to the size of area measured which is represented by each pixel. Spectral refer to the range of wavelength the sensor is sensitive to. Radiometric refer to the difference in radiation intensity. Temporal characteristics refer to the time of image acquisition. These resolutions need to be considered based on the purpose of the mapping.

## Application: Example of Landsat and Sentinel for Urban Heat Island (UHI)

With the growing technology, remote sensing becomes more advanced and freely available. The development of single sensor to multiple sensors allows spatial researcher to do environmental and social research using it. The example of application includes biodiversity monitoring, crop classification, hazards modelling, Urban Heat Island monitoring, LULC classification, and carbon sequestration modelling [@roy2017]. Sometimes people compare and combine multiple sensors from different platform to get accurate and comprehensive results because different sensors capturing the same area might get different reflectance values. Examples of known satellites for research are Terra, MODIS, SPOT, Landsat, and Sentinel [@toth2016a].

The paper by [@rech2024] gives example of using Landsat 8 TIRS band for mapping Surface Urban Heat Islands (SUHI) and assess the SUHI relation to albedo, elevation, land surface emissivity, and vegetation cover across Local Climate Zones (LCZ) in Florianopolis, Brazil. The paper assessing the variability of SUHI between day and night, different LCZ and different surface using multiple statistical approaches. Although the paper mentioned using Practical Single-Channel (PSC) algorithm to derive LST, the result does not explain the accuracy of the methods or the LST before used for analysis and instead only focuses on the variability with the parameters. Since the study area is a humid region, the use of PSC method give concern on its reliability. However, I think the author has tried it best to find images with low cloud cover and no rain. Unfortunately, there’s only one pair that meets these criteria, so it’s not feasible to conduct the study for different seasons. Moreover, since the TIRS band already resampled to 30 meters, I think it would be good if they zoom in to some specific areas to show variability.

Meanwhile, the paper by [@hidalgogarcía2021] used Sentinel-3 to Meanwhile, the paper by [@hidalgogarcía2021] used Sentinel-3 to derive LST and applied Split-Window Correction for assessing Urban Heat Island and factors contributing to it in Granada, Spain. Different from previous one, this study compares the value derived from Sentinel-3 with in-situ analysis. The result shows Sentinel-3 temperature is a little bit higher. The study also conduct analysis for different seasons because Sentinel-3 temporal resolution is daily giving more available data to used. However, the Sentinel-3 1 km resolution might not be as detailed as Landsat 8, even though the author had tried to resample it to 100 meters.

## Reflection: Challenges in Remote Sensing and Potential Future Study

Since I have been learning about remote sensing on my undergraduate degree before, the material about sensors and electromagnetic reflectance are already familiar for me. I also have used some remote sensing data for my research and since the first time I know about it, I always think remote sensing mapping is a cheaper method for large area compared to other mapping techniques. However, when I did the practical using SNAP for Sentinel-2 and Landsat-8 data, I started to think even though the medium spatial resolution remote sensing images are freely available, we still need high specification computer to process it because one tiles comprised of several bands are huge and my laptop somewhat need to work hard to do the resampling and other practical. It also made me realise that it’s not quite efficient to do preprocessing of these images from scratch when you only want to do research on very small area especially when the boundary does not overlap perfectly with the image. I think using Google Earth Engine (GEE) which would be explained in the later weeks is better because they provide some already pre-processed images and its based-on cloud, so you don’t need high specification computer. Beside this issue, I also think that this ‘cheaper method’ only applies to regional-based analysis that can use medium spatial resolution like Landsat and Sentinel-2. Meanwhile, if you want to do a detailed analysis on city like how the UHI effect on different surface and LCZ, especially for building level, it will need high spatial resolution which are mostly still commercial. The resampling methods may give us immediate solution for this although we still need to consider the impact of each method that may affect the analysis. However, despite all the challenges in remote sensing approaches, I still think it’s the most robust method in the present that can give comprehensive result when its used and combined with other dataset appropriately. To this day, I still have a goal to do UHI analysis on building level using open-source remote sensing data. I believe remote sensing technology would develop even further that gives more better resolution from the existing ones.
