# Xaringan Presentation and Quarto Book

```{r xaringan-embed, echo=FALSE}
xaringanExtra::embed_xaringan(
  url = "https://jasminemhdn.github.io/CASA0023/presentation2.html#1",
  ratio = "4:3"
)
```

## Reflection: 

This is my first time learning how to make presentation by writing it in Xaringan instead of directly place the words and figures in slides like in Microsoft Powerpoint. The Xaringan might quite simple, but I actually prefer a simple presentation. It is good that I don't have to think about symmetrical placement of the word and figures because they are already placed automatically and I just have to specify the location using middle, center, or .pull-left and .pull-right. Also, the use of github making it easier to collaborate with colleagues and can be accessible for everyone at anytime and anywhere. My favorite part is the tab part in single slides. Usually for information like resolutions for different instrument (slides 4), I would display it as a table, but from now on I think I will use tab a lot since it gives more space for explanation but because they are placed in one slides it makes more efficient.