# Remote Sensing Application to Support Policy

## Summary: Zoning-based Public School Admission Policy in Bandung, Indonesia

Prior to 2015, Indonesia used merit-based public school admission policy in which students' national exam result will be used for admission to higher education level. This policy result in creating some favorite and popular schools including in Bandung. However, as to support the Goals of SDGs 5. Quality Education, reduce the traffic congestion in peak hour, increase the quality of all the school to the same level, eliminate school's exclusivity, and increase students' mental health, the Mayor of Bandung changed the regulation of public high school admission to distance-based through Perwali Kota Bandung No. 361 2015. This new regulation soon was adapted nationally by the Minister of Education and Culture in 2017 through Permendikbud No. 17 2017. This policy regulates that school should accept at least 90% students with house located in the zone near school. The zone itself will be defined by each cities. For Bandung, the old regulation (Perwali Kota Bandung No. 361 2015) was replaced by Perwali Kota Bandung No. 57 2021. However, the public sentiment of this policy is divided into pro and cons since the first time the policy has been applied [@hoerudin2019]. The issue in applying this policy is that the school not distributed evenly in the cities. Therefore, there is always schools with less applicants and the other schools with applicants more than its capacity.

## Application: School Location Spatial Analysis

To support the zoning-based public school policy using remote sensing and GIS, one of the way is through assessing the school location spatial analysis. A paper by [@sakti2021] demonstrated it by analysing school location in West Java, the province where Bandung is located. The study considering accessibility, comfort, and hazard susceptibility to assess the school location. For the accessibility factor, they use road network, population density, and residential areas, meanwhile for comfort factor, they use air pollution, land surface temperature, and noise pollution. Lastly, for hazard susceptibility, they considering COVID-19, flood, landslide, and earthquakes. Remote sensing dataset play important role to produce those maps such as Sentinel-5P for air pollution, Landsat 8 for land surface temperature, CHIRPS for rainfall, Worlpop for population density, and ALOS for elevation. Several methods was used such as network analysis, Multi Criteria Decision Analysis (MCDA), and classification. Beside assessing the location of school, they also suggesting location to build new schools that meet those criterias.

## Reflection: Education Geography

The school location in Bandung is one of the topic that I like the most. I am very happy to know that remote sensing and GIS can be used as approaches to support policy like this. Even though, I am not sure small cities could be benefit from it since the open access remote sensing data with high spatial resolution is hardly available, while medium to low spatial resolution can not specify the area within the cities. While reading the paper, I found out that the key word for assessing school location can also be called education geography and there already a lot of papers conducting research regarding school location distribution or school accessibility in many countries all over the world.
