# Supervised vs Unsupervised Classification

## Summary: Difference Between Supervised and Unsupervised Classification

Classification is the most common methods used in remote sensing. Example of basic classification is land cover classification where the pixel is classified into each category such as bare lands, built up areas, forests, agricultures, and water bodies. In general, image classification is divided into two types: Supervised and Unsupervised. Below is the explanation of each classification methods:

### Supervised Classification

Supervised classification makes classes based on pattern of previous information. Machine learning algorithm is categorised as supervised classification. Manual classification requires us to define each class and create area of interest (AOI) as examples for each classes, while machine learning methods use training data to make classification. Examples of supervised classification methods are Maximum Likelihood, Support Vector Machine (SVM), and Random Forest (RF).

-   Maximum Likelihood: probabilistic method that assumes each class has normal distribution.

-   Support Vector Machine (SVM): machine learning classifier that define the best boundary (hyperplane) to separate each class.

-   Random Forest (RF): machine learning algorithm that builds multiple decision trees.

### Unsupervised Classification

Unsupervised classification is a method that make classification based on the same spectral properties. We don't have to define each class and know a priori information, but we have to determine the number of class or cluster that we want to create through the classification process. Example of unsupervised clustering is K-Means and ISODATA.

-   K-Means: assign pixel to k clusters based on similarity of pixel value or digital number.

-   ISODATA: adjust the number of clusters dynamically.

## Application: Machine Learning Techniques in Habitat Suitability

Paper by [@santoso2023] assess the suitability of the developed Grizzled leaf monkey habitat in Java Island, Indonesia using combination of Random Forest (RF), Support Vector Machine (SVM), and Maximum Entropy (MaxEnt). A total of 12 remote sensing product were used in this studies including MODIS LST, MODIS LC, CHIRPS, FLDAS, SRTM, HydroSHEDS, Landsat 8, VIIRS, Sentinel-5P and Worldpop. It is really impresive to me that nowadays image classification and machine learning methods are not only applied to land cover mapping, but for a variety use including habitat suitability. This paper give a comprehensive analysis by using massive dataset that assess the climate, topography, ecology, and anthropogenic factors to habitat suitability. They also integrating three different machine learning algorithms which I think can be good for eliminating limitation of each of the methods. However, I think it can be great if they use more technique in this integration rather than using unweighted one. I also like the layouting of the maps which is very creative and inspiring especially for Surili Habitat Against Population Prediction 2040. Things that I am curious about the method is thy why they use different vegetation index like NDVI, SAVI, and leaf area index because it potentially creating multicollinearity and affecting the result. I think it will be better if they can use the same procedure as [@rahimianboogar2019] in which they do proper data preprocessing and processing to predict habitat suitability of Juniperus spp. In the Southern Zagros Mountains of Iran by utilising SVM and MaxEnt. Both papers actually use massive dataset, but there are difference in parameters that they used in which [@rahimianboogar2019] divided the parameters into climate, topography, soil, and environmental factors. It will be interesting if [@rahimianboogar2019] also include anthropogenic factors in their study. Overall, I think what has been missing from both papers is that they only include AUC and ROC as accuracy assessment, it will be good if they include more accuracy assessment for more thorough analysis.

## Reflection: Remote Sensing for Thematic Mapping

As someone who really likes thematic mapping, I am extremely happy that remote sensing classification has been evolved to variety of topic such as habitat suitability. The method is not only glued to land cover analysis. Furthermore with the growth of machine learning, we do not have to manually create class based on AOI for doing unsupervised classification which also requires us interpret the analysis visually. But, unsupervised classification also provides a challenge because it depends on the availability of training dataset and the accuracy also depends on the quality of the dataset. Nevertheless, with the growth of dataset, I believe there will be more analysis that we can conduct using machine learning and remote sensing such as plastic waste detection in water bodies and informal settlement detection which I really interested.
