# Remote Sensing Image Corrections and Enhancement

## Summary: Type of Corrections and Enhancement

Remote sensing images contain bias and error from earth's rotation, terrain and atmospheric condition that may affect the surface reflectance. Below is the summary of correction applied to remote sensing for the pre-processing process.

### Geometric Correction

Geometric correction is used to remove or reduce the effect of Earth rotation and terrain during the scanning of an image. The table below shows the example of geometric correction approaches.

| **Methods** | **Description** |
|------------------------------------|------------------------------------|
| Georeferencing | The process of link an image to a map projection by using geometric transformation. Points in identical places that captured in two different images or systems is the key points in georeferencing. |
| Geocoding | The process use to transform row/column structure of the image (resampling). Geocoding is required to combine different images. |

: Geometric Correction Methods

### Radiometric Correction

The radiometric correction deals with the radiance values of reflected polychromatic solar radiation and the emitted thermal radiance from Earth's surface. The atmosphere cause the radiance value to be altered when recorded by the satellite. In general the radiometric correction is divided into cosmetic correction and atmospheric correction.

| **Methods** | **Description** |
|------------------------------------|------------------------------------|
| Cosmetic | Cosmetic correction use filters, image stretching, and image enhancement to correct visible errors and noise in the image data without involving atmospheric model. |
| Atmospheric | Atmospheric correction is applied to remove the atmospheric effect by using models. There are two types of this correction: relative (does not require atmospheric component) and absolute (require atmospheric component). |

: Radiometric Correction Methods

### Enchancement

Image enhancement is the procedure of improving the quality and information content of original data (Haldar, 2018). The table below explain each of the methods.

| **Methods** | **Description** |
|------------------------------------|------------------------------------|
| Contrast Enhancemenet | Contrast enhancement or stretching is performed by linear transformation expanding the original range of gray level. |
| Spatial Filtering | Spatial filtering improves the naturally occurring linear features like fault, shear zones, and lineaments. |
| Density Slicing | Density slicing converts the continuous gray tone range into a series of density intervals marked by a separate color or symbol to represent different features. |
| FCC | FCC is commonly used in remote sensing compared to true colors because of the absence of a pure blue color band because further scattering is dominant in the blue wavelength. |

: Image Enhancement Methods

## Application: Correction for Assessing Solar PV Potential

The paper by Sakti et al. (2022) model the potential of solar PV development of each building in Bandung, Indonesia by considering the energy potential and energy needed to generate electricity. The paper use shortwave radiation to calculate the solar energy potential in each building, but because sunlight that reach the building is not fully optimum, several correction methods should be applied by using Aerosol Optical Depth (AOD), precipitation, and Land Surface Temperature (LST). I think this paper is very interesting to support the government goals in transitioning to renewable energy. It provides a depth analysis on the solar energy potential and the electricity that needs to be generated. In the analysis on the solar energy potential, the author provides hillshade analysis and atmospheric correction that might alter the sunlight in reaching the rooftop. However, the author assumes constant value of daily data and does not consider cloud and humidity in the atmospheric correction which I think is important because beside needing optimum sunlight, we also have to make sure that the sun is shining almost all year round for it to be effective. Another paper that I found regarding this topic is by Lodhi et al. (2024) that assess the solar PV potential using Mask R-CNN and DeepLabV3 deep learning models on high resolution Google Earth Imagery and generating DEM from 10 meter resolution Sentinel-1 for estimating solar radiation. Both papers have same goals with very different approaches, but still applies image correction before extracting the value of solar raditation. Lodhi et al. (2024) uses noise removal, radio metric calibration, and terrain correction to Sentinel-1. I think for assessing solar PV potential, radiometric correction especially atmospheric correction is very important as it is connected directly to sun radiation.

## Reflection: The Overlook Importance of Image Correction

As I saw earlier in the application of atmospheric and radiometric correction in extracting solar radiation for assessing solar PV potential, image correction is really importance to generating real value. However, I find it these corrections are rarely talked about in the remote sensing application paper. But maybe because these days, a lot of remote sensing products have already been applied with image correction. Still, it is still importance to understand about the effect of atmosphere to the reflectance and how to use proper correction methods in the images. Beside for assessing solar PV potential, I think image correction and enhancement also important when doing study about Urban Heat Island (UHI), carbon sequestration, or mineral detection.
