# Introduction to Synthetic Aperture Radar (SAR)

## Summary: How SAR Works

Synthetic Aperture Radar is an active remote sensing sensor that can generate it's own energy, can penetrate through the clouds and operates day and night. SAR is using microwave frequencies to capture image of Earth's surface. SAR works by emitting radar pulses toward Earth's surface, then the pulses interact with surfaces, scattering signals differently based on material properties, the sensors then detect and process returned signals to create images based on intensity, phase, and polarization. The table below shows the common SAR frequency bands

| Band | Frequency | Wavelength | Satellite Examples | Application |
|---------------|---------------|---------------|---------------|---------------|
| X-band | 8–12 GHz | \~3 cm | TerraSAR-X, Cosmo-SkyMed | Urban areas, high spatial detail |
| C-band | 4–8 GHz | \~5.6 cm | Sentinel-1, RADARSAT | Agriculture, flood mapping, rapid change |
| L-band | 1–2 GHz | \~23 cm | ALOS PALSAR, SAOCOM | Vegetation, forests, subsurface features |

## Application: InSAR for Disaster Mapping

One of the most common application of SAR is for disaster or post disaster mapping especially for natural hazard that relate to deformation or earth movement such as earthquake, land subsidence, and volcanic eruption. The paper by Sidiq et al. (2021) monitor land subsidence along the North Coast of Java Island in Indonesia from 2016 to 2020 by utilising C-Band Sentinel-1 and elevation data and Small Baseline Subset (SBAS) algorithm. Meanwhile, Tsuji et al. (2009) using L-band of ALOS PALSAR to compared the surface deformation before and after 2006 Yogyakarta earthquakes in Indonesia and Nuranjo et al. (2023) is the first paper to detected areas affected by volcanic ash deposits after an eruption in Mount Taal, Philippines using Temporal Decorrelation Model (TDM) applied for C-band of Sentinel-1. All of these papers Interferometric Synthetic Aperture Radar (InSAR) with different approaches. I think what makes SAR interesting in disaster mapping is that it allow us to do mapping in remote areas that hardly can be accessed if using terrestrial mapping or GNSS. Furthermore, the Sentinel-1 which is openly available allows us to do semi real-time mapping after the disaster happened so we can calculate a rough estimates of the affects and potential losses by it which make us more resilient to the disaster. However, it is unfortunate that Sentinel-1 only operates on C-band that has limitation in temporal decorrelation especially in vegetation areas compared to L-band as appointed by Sidiq et al. (2021) and Nuranjo et al. (2023). Tsuji et al. (2009) use L-band from ALOS PALSAR so it does not suffered the same problem with the other two studies, but ALOS PALSAR was discontinued in 2011 and ALOS PALSAR 2 data is limited to commercial. Sadly, the paper by Sidiq et al. (2021) and Tsuji et al. (200) do not provide accuracy assessment or compare the methods of InSAR with ground mapping. It would be great if we know how differ the land subsidence monitoring between the methods and how to improve the accuracy of InSAR to be the same level as ground monitoring. These two studies might adapting the approach by Nuranjo et al. (2023) that assessing their result with the field data from the officials. In the papers, they showed that they achieve more than 80% accuracy for their result, which is a good thing.

## Reflection: Upcoming NASA-ISRO NISAR

I think SAR is really interesting approaches to do time series mapping because it does not affected by weather and not rely on sun energy. It also can mapping remote areas in disaster mapping, so we can do almost real-time monitoring that does not requires lot of resources and allocation. However, understanding SAR and it's data processing are extremely difficult and for now we can only use Sentinel-1 that is open dataset while we know that Sentinel-1 C-band is highly sensitive in vegetated areas and ALOS PALSAR 2 is limited to commercial. I tried to find other open SAR dataset that use L-band and find out NASA-ISRO NISAR that using L-band and S-band is expected to launch this year. I thin it will be massively used if the satellite has been launched later because the S-band provide the moderate performance between C-band and L-band so it can be more balanced and I am really excited on how these SAR dataset can be used for other mapping such as mapping ancient settlements, detection of buried archaeological structures, assessing building structure and stability, and carbon stock estimation. In January 2025, NASA-ISRO NISAR had finished all preliminary checkout and is expected to be launched in March 2025.
